# Generated by Django 4.2.4 on 2023-08-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
