# Generated by Django 4.2.5 on 2023-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_comment_options_comment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.CharField(default='nodate', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
    ]
