# Generated by Django 4.0.5 on 2023-09-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blogpost_date_blogpost_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_image',
            field=models.ImageField(default='blog_images/authorlogo.jpg', upload_to='blog_images/'),
        ),
    ]
