# Generated by Django 4.0.5 on 2023-09-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_commentvalidation_comment_comment_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_validation',
        ),
        migrations.DeleteModel(
            name='CommentValidation',
        ),
    ]
